name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
